apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2023-06-13T19:59:41Z"
  name: webapp
  namespace: default
  resourceVersion: "153068"
  uid: 7e121940-b7b1-42cf-a8ce-14ffc51574cb
spec:
  maxReplicas: 20
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 85
        type: Utilization
    type: Resource
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
status:
  conditions:
  - lastTransitionTime: "2023-06-13T19:59:57Z"
    message: the HPA controller was able to get the target's current scale
    reason: SucceededGetScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2023-06-13T20:00:13Z"
    message: 'the HPA was unable to compute the replica count: failed to get cpu utilization:
      missing request for cpu'
    reason: FailedGetResourceMetric
    status: "False"
    type: ScalingActive
  currentMetrics: null
  currentReplicas: 10
  desiredReplicas: 10
  lastScaleTime: "2023-06-13T19:59:57Z"
