apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  completions: 10
  template:
    spec:
      containers:
      - name: hello-job
        image: busybox
        command: ["/bin/sh", "-c", "echo 'Hello I am from job'; exit"]
      restartPolicy: OnFailure
