apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-yossi
spec:
  volumes:
  - name: redis-data
    emptyDir: {}
  containers:
  - name: redis
    image: redis:alpine
    volumeMounts:
      - name: redis-data
        mountPath: /data/redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
