apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  labels:
    app: nginx-resolver
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
spec:
  selector:
    app: nginx-resolver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

