apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    name: myapp
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["sleep", "1000"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
